[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pandocfilters"
version = "0.1.0"
requires-python = ">= 3.10"

[project.scripts]
tikz = "filters.tikz:main"
